const test=require('node:test');const assert=require('node:assert/strict');const GooglePlay=require('../google-play-provider.js');
const product=id=>({productId:id,displayName:id,description:'desc',displayPrice:'¥100',productType:'nonConsumable'});
function harness(overrides={}){const events=[],verified=[],acknowledged=[];let purchases=overrides.purchases||[];
  const plugin={loadProducts:async()=>({products:GooglePlay.PRODUCT_IDS.map(product)}),purchase:async({productId})=>overrides.purchaseResult||{status:'purchased',productId,purchaseToken:`token-${productId}`},restorePurchases:async()=>({purchases}),acknowledgePurchase:async({purchaseToken})=>acknowledged.push(purchaseToken)};
  const api={identity:async()=>({playerId:'op_player'}),verifyPurchase:async value=>{if(overrides.verifyError)throw Object.assign(new Error('rejected'),{status:403});verified.push(value);return {profile:{}};}};
  return {provider:GooglePlay.createProvider({plugin,api,onState:value=>events.push(value)}),events,verified,acknowledged};}
test('Android商品取得はGoogle Play価格を返す',async()=>{const h=harness(),result=await h.provider.loadProducts();assert.equal(result.products.length,6);assert.equal(result.products[0].displayPrice,'¥100');});
test('単品・パック・広告削除・セット購入は検証後だけacknowledge',async()=>{for(const id of GooglePlay.PRODUCT_IDS){const h=harness(),result=await h.provider.purchaseProduct(id);assert.equal(result.purchased,true);assert.equal(h.verified[0].productId,id);assert.deepEqual(h.acknowledged,[`token-${id}`]);}});
test('キャンセル・保留・検証失敗ではacknowledgeしない',async()=>{for(const purchaseResult of [{status:'cancelled'},{status:'pending'}]){const h=harness({purchaseResult}),result=await h.provider.purchaseProduct('REMOVE_ADS');assert.equal(result.purchased,false);assert.equal(h.acknowledged.length,0);}const failed=harness({verifyError:true}),result=await failed.provider.purchaseProduct('REMOVE_ADS');assert.equal(result.purchased,false);assert.equal(failed.acknowledged.length,0);});
test('不正商品・連打を拒否',async()=>{const h=harness();assert.equal((await h.provider.purchaseProduct('BAD')).reason,'unknownProduct');let release;const slow=GooglePlay.createProvider({plugin:{purchase:()=>new Promise(r=>release=r)},api:{identity:async()=>({playerId:'p'})}});const first=slow.purchaseProduct('REMOVE_ADS');assert.equal((await slow.purchaseProduct('REMOVE_ADS')).reason,'busy');release({status:'cancelled'});await first;});
test('復元はPlay購入情報を全件サーバー検証',async()=>{const purchases=[{productId:'SKILL_PACK_01',purchaseToken:'token-pack'},{productId:'REMOVE_ADS',purchaseToken:'token-ads'}],h=harness({purchases}),result=await h.provider.restorePurchases();assert.equal(result.restored,true);assert.equal(result.count,2);assert.equal(h.verified.length,2);assert.equal(h.acknowledged.length,2);});
test('Android native pluginだけを選択する',()=>{assert.ok(GooglePlay.nativePlugin({Capacitor:{getPlatform:()=> 'android',Plugins:{NyanGooglePlay:{ok:true}}}}));assert.equal(GooglePlay.nativePlugin({Capacitor:{getPlatform:()=> 'ios'}}),null);});
