const test=require('node:test'),assert=require('node:assert/strict');
const mod=import('../server/ranked-progression.mjs');
const base=async(rp=0,id='2026-09')=>{const {normalizeRanked}=await mod;const p=normalizeRanked({version:1,ownedCatSkins:['default'],ownedDogSkins:['default'],equippedAppearance:{}},Date.parse(id+'-15T00:00:00+09:00'));p.ranked.rp=rp;p.ranked.rank='forged';return p;};
test('RP増減、最低値、昇格・降格はRPから再計算',async()=>{const {applyRankedResult}=await mod;
 let a=applyRankedResult(await base(0),{matchId:'m1',won:true,completedAt:Date.parse('2026-09-15T00:00:00+09:00')});assert.equal(a.profile.ranked.rp,10);
 a=applyRankedResult(await base(100),{matchId:'m2',won:false,completedAt:Date.parse('2026-09-15T00:00:00+09:00')});assert.deepEqual([a.profile.ranked.rp,a.profile.ranked.rank],[94,'bronze']);
 a=applyRankedResult(await base(245),{matchId:'m3',won:true,completedAt:Date.parse('2026-09-15T00:00:00+09:00')});assert.deepEqual([a.profile.ranked.rp,a.profile.ranked.rank],[255,'gold']);
 a=applyRankedResult(await base(451),{matchId:'m4',won:false,completedAt:Date.parse('2026-09-15T00:00:00+09:00')});assert.deepEqual([a.profile.ranked.rp,a.profile.ranked.rank],[445,'gold']);
 a=applyRankedResult(await base(2),{matchId:'m5',won:false,completedAt:Date.parse('2026-09-15T00:00:00+09:00')});assert.equal(a.profile.ranked.rp,0);
});
test('勝利は5コインと戦績、敗北はコインなし、フレームは永久所持',async()=>{const {applyRankedResult}=await mod;
 const win=applyRankedResult(await base(95),{matchId:'w',won:true,completedAt:Date.parse('2026-09-15T00:00:00+09:00')});assert.equal(win.profile.serverNyanCoins,5);assert.equal(win.profile.ranked.seasonWins,1);assert.ok(win.profile.ownedProfileFrames.includes('rank_silver'));
 const lose=applyRankedResult(win.profile,{matchId:'l',won:false,completedAt:Date.parse('2026-09-15T00:00:00+09:00')});assert.equal(lose.profile.serverNyanCoins,5);assert.equal(lose.profile.ranked.seasonLosses,1);assert.ok(lose.profile.ownedProfileFrames.includes('rank_silver'));
});
test('勝敗確定月へ加算し、ダイヤ報酬確定後500RPへ再配置',async()=>{const {applyRankedResult}=await mod,p=await base(864,'2026-09');
 const a=applyRankedResult(p,{matchId:'oct',won:true,completedAt:Date.parse('2026-10-01T00:02:00+09:00')});const sep=a.profile.seasonHistory.find(h=>h.seasonId==='2026-09');
 assert.deepEqual([sep.finalRP,sep.finalRank,sep.rewardAmount],[864,'diamond',1200]);assert.deepEqual([a.profile.ranked.seasonId,a.receipt.seasonId,a.profile.ranked.rp],["2026-10","2026-10",510]);
});
test('マスター未設定は資格固定、設定後に確定し所持済みだけ1500コイン',async()=>{const {normalizeRanked}=await mod,p=await base(1100,'2026-09');
 let n=normalizeRanked(p,Date.parse('2026-10-01T00:01:00+09:00'),{},{}),h=n.seasonHistory[0];assert.equal(h.rewardStatus,'pendingConfiguration');assert.equal(h.finalRP,1100);
 n=normalizeRanked(n,Date.parse('2026-10-02T00:00:00+09:00'),{'2026-Q3':'cat_kaitou'},{cat_kaitou:'catSkin'});h=n.seasonHistory[0];assert.deepEqual([h.rewardType,h.rewardSkinId,h.rewardStatus],['skin','cat_kaitou','claimable']);
 n.ownedCatSkins.push('cat_kaitou');n.seasonHistory[0].rewardStatus='pendingConfiguration';n.seasonHistory[0].rewardSkinId=null;
 n=normalizeRanked(n,Date.parse('2026-10-03T00:00:00+09:00'),{'2026-Q3':'cat_kaitou'},{cat_kaitou:'catSkin'});assert.deepEqual([n.seasonHistory[0].rewardType,n.seasonHistory[0].rewardAmount],['coins',1500]);
});
test('シーズン報酬は二重受取不可',async()=>{const {normalizeRanked,claimSeasonReward}=await mod,p=await base(864,'2026-09');let n=normalizeRanked(p,Date.parse('2026-10-01T00:00:00+09:00'));
 const first=claimSeasonReward(n,'2026-09',Date.parse('2026-10-02T00:00:00+09:00'));assert.equal(first.profile.serverNyanCoins,1200);
 const twice=claimSeasonReward(first.profile,'2026-09',Date.parse('2026-10-03T00:00:00+09:00'));assert.equal(twice.error,'already_claimed');assert.equal(twice.profile.serverNyanCoins,1200);
});
test('既存オンラインプロフィールは資産を維持してランク項目を補完',async()=>{
 const {normalizeRanked}=await mod;const old={version:1,playerId:'old',ownedCatSkins:['default','cat_kaitou'],ownedDogSkins:['default'],equippedAppearance:{catSkinId:'cat_kaitou',dogSkinId:'default'},cpuUnlockClaims:{cat_hard_10wins:'unverified-client-claim'}};
 const migrated=normalizeRanked(old,Date.parse('2026-09-15T00:00:00+09:00'));
 assert.equal(migrated.version,2);assert.equal(migrated.ranked.rp,0);assert.equal(migrated.ranked.rank,'bronze');assert.equal(migrated.ranked.seasonId,'2026-09');
 assert.deepEqual(migrated.ownedCatSkins,old.ownedCatSkins);assert.deepEqual(migrated.equippedAppearance,old.equippedAppearance);assert.ok(migrated.ownedProfileFrames.includes('rank_bronze'));
});
test('未設定マスター報酬APIは受取を拒否して資格を保持',async()=>{
 const {profileRequest,digestToken}=await import('../server/online-profile.mjs');
 const values=new Map(),storage={get:async key=>structuredClone(values.get(key)),put:async(key,value)=>{for(const [k,v] of typeof key==='string'?[[key,value]]:Object.entries(key))values.set(k,structuredClone(v));}};
 const token='ef'.repeat(32),headers={Authorization:`Bearer ${token}`},key=`profile:${await digestToken(token)}`;
 const profile=await base(1100,'2026-09');profile.playerId='master-player';values.set(key,profile);values.set('profile-key:master-player',key);
 const response=await profileRequest(storage,new Request('https://test/season-reward',{method:'POST',headers,body:JSON.stringify({seasonId:'2026-09'})}),{now:Date.parse('2026-10-02T00:00:00+09:00')});
 assert.equal(response.status,409);const body=await response.json();assert.equal(body.error,'pending_configuration');assert.equal(body.profile.serverNyanCoins,0);
 assert.deepEqual([body.reward.seasonId,body.reward.finalRank,body.reward.finalRP,body.reward.rewardStatus],['2026-09','master',1100,'pendingConfiguration']);
});
test('プロフィールフレームAPIは所持済みだけ装備可能',async()=>{
 const {profileRequest}=await import('../server/online-profile.mjs');
 const values=new Map(),storage={get:async key=>structuredClone(values.get(key)),put:async(key,value)=>{for(const [k,v] of typeof key==='string'?[[key,value]]:Object.entries(key))values.set(k,structuredClone(v));}};
 const headers={Authorization:`Bearer ${'12'.repeat(32)}`};
 await profileRequest(storage,new Request('https://test/register',{method:'POST',headers,body:'{}'}),{now:Date.parse('2026-09-01T00:00:00+09:00')});
 let response=await profileRequest(storage,new Request('https://test/profile-frame',{method:'POST',headers,body:JSON.stringify({frameId:'rank_master'})}),{now:Date.parse('2026-09-01T00:00:00+09:00')});assert.equal(response.status,400);
 response=await profileRequest(storage,new Request('https://test/profile-frame',{method:'POST',headers,body:JSON.stringify({frameId:'rank_bronze'})}),{now:Date.parse('2026-09-01T00:00:00+09:00')});assert.equal(response.status,200);assert.equal((await response.json()).profile.equippedProfileFrameId,'rank_bronze');
});
test('正式random結果だけを対象にし、切断敗北と時間切れは含める',async()=>{
 const {eligibleRankedResult}=await mod,match={matchType:'randomMatch'},normal={status:'finished',hasStarted:true,result:{winner:'cat'}};
 assert.equal(eligibleRankedResult(match,normal),true);
 assert.equal(eligibleRankedResult(match,{...normal,result:{winner:'police',finishReason:'disconnectForfeit'}}),true);
 assert.equal(eligibleRankedResult(match,{...normal,result:{winner:'cat',finishReason:'turnTimeout'}}),true);
 assert.equal(eligibleRankedResult({matchType:'roomMatch'},normal),false);
 assert.equal(eligibleRankedResult(match,{...normal,hasStarted:false}),false);
 assert.equal(eligibleRankedResult(match,{...normal,status:'invalid',result:{finishReason:'serverInvalid'}}),false);
 assert.equal(eligibleRankedResult(match,{...normal,result:{winner:'cat',finishReason:'abortedBeforeStart'}}),false);
});
