const test=require('node:test');const assert=require('node:assert/strict');const {webcrypto}=require('node:crypto');globalThis.crypto||=webcrypto;
class Store{values=new Map();async get(k){return structuredClone(this.values.get(k));}async put(k,v){for(const [key,val] of typeof k==='string'?[[k,v]]:Object.entries(k))this.values.set(key,structuredClone(val));}async transaction(fn){return fn(this);}}
const googleModule=import('../server/google-play-verification.mjs'),profileModule=import('../server/online-profile.mjs');
async function setup(){const {initialProfile}=await profileModule,storage=new Store(),profile=initialProfile({},'P1'),profileKey='profile:test';await storage.put(profileKey,profile);return {storage,profile,profileKey};}
const receipt=(productId,token='purchase-token-1')=>({purchaseToken:token,productId,orderId:'order',purchaseDate:1,packageName:'jp.nyanchase.game',accessToken:'access'});
test('全6商品を共通entitlementへ付与',async()=>{const {applyVerifiedGooglePlayPurchase}=await googleModule;for(const [i,id] of ['SKILL_CAT_FAKE_PAW','SKILL_POLICE_GROUP_SEARCH','SKILL_POLICE_DASH','SKILL_PACK_01','REMOVE_ADS','REMOVE_ADS_PLUS_SKILL_PACK_01'].entries()){const f=await setup(),result=await applyVerifiedGooglePlayPurchase({...f,purchaseToken:`token-${i}-long`,productId:id,verify:async()=>receipt(id,`token-${i}-long`),acknowledge:async()=>true});assert.ok(result.profile.skillEntitlements.purchasedProductIds.includes(id));}});
test('purchaseToken再送は冪等、別playerへの流用は拒否',async()=>{const {applyVerifiedGooglePlayPurchase}=await googleModule,f=await setup(),verify=async()=>receipt('REMOVE_ADS','same-token-long');const one=await applyVerifiedGooglePlayPurchase({...f,purchaseToken:'same-token-long',productId:'REMOVE_ADS',verify});const two=await applyVerifiedGooglePlayPurchase({...f,profile:one.profile,purchaseToken:'same-token-long',productId:'REMOVE_ADS',verify});assert.equal(two.duplicate,true);await assert.rejects(()=>applyVerifiedGooglePlayPurchase({storage:f.storage,profileKey:'other',profile:{...f.profile,playerId:'op_other'},purchaseToken:'same-token-long',productId:'REMOVE_ADS',verify}),/already_claimed/);});
test('アカウント不一致・検証失敗・不正商品を拒否',async()=>{const {applyVerifiedGooglePlayPurchase}=await googleModule,f=await setup();await assert.rejects(()=>applyVerifiedGooglePlayPurchase({...f,purchaseToken:'purchase-token-x',productId:'REMOVE_ADS'}),/unavailable/);await assert.rejects(()=>applyVerifiedGooglePlayPurchase({...f,purchaseToken:'purchase-token-x',productId:'BAD',verify:async()=>receipt('BAD')}),/not_verified/);await assert.rejects(()=>applyVerifiedGooglePlayPurchase({...f,purchaseToken:'purchase-token-x',productId:'REMOVE_ADS',verify:async()=>({...receipt('REMOVE_ADS','purchase-token-x'),obfuscatedExternalAccountId:'op_other'})}),/account_mismatch/);});
test('Developer API productV2の購入済み応答だけを検証',async()=>{const {verifyGooglePlayPurchase}=await googleModule,calls=[],keyPair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']),pkcs8=await crypto.subtle.exportKey('pkcs8',keyPair.privateKey);const env={GOOGLE_PLAY_PACKAGE_NAME:'jp.nyanchase.game',GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL:'svc@example.com',GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY:`-----BEGIN PRIVATE KEY-----\n${Buffer.from(pkcs8).toString('base64')}\n-----END PRIVATE KEY-----`};
  const fetchFn=async(url,options)=>{calls.push({url,options});if(url.includes('oauth2.googleapis.com'))return {ok:true,json:async()=>({access_token:'access'})};return {ok:true,json:async()=>({purchaseStateContext:{purchaseState:'PURCHASED'},productLineItem:[{productId:'REMOVE_ADS'}],orderId:'order',purchaseCompletionTime:'2026-09-18T00:00:00Z',obfuscatedExternalAccountId:'op_player'})};};
  const result=await verifyGooglePlayPurchase({purchaseToken:'purchase-token-long',productId:'REMOVE_ADS'},{env,fetchFn});assert.equal(result.productId,'REMOVE_ADS');assert.match(calls[1].url,/productsv2\/tokens\/purchase-token-long$/);assert.match(calls[1].options.headers.Authorization,/^Bearer /);
});
test('単品所有後のPACK購入でもスキルを重複させない',async()=>{const {applyVerifiedGooglePlayPurchase}=await googleModule,{resolveServerOwnedSkillIds}=await import('../server/skill-entitlements.mjs'),f=await setup();let one=await applyVerifiedGooglePlayPurchase({...f,purchaseToken:'token-single-long',productId:'SKILL_CAT_FAKE_PAW',verify:async()=>receipt('SKILL_CAT_FAKE_PAW','token-single-long')});let pack=await applyVerifiedGooglePlayPurchase({...f,profile:one.profile,purchaseToken:'token-pack-long',productId:'SKILL_PACK_01',verify:async()=>receipt('SKILL_PACK_01','token-pack-long')});assert.equal(new Set(resolveServerOwnedSkillIds(pack.profile.skillEntitlements)).size,3);});
