const test=require('node:test');const assert=require('node:assert/strict');const {webcrypto}=require('node:crypto');globalThis.crypto||=webcrypto;
class Store{values=new Map();async get(k){return structuredClone(this.values.get(k));}async put(k,v){for(const [key,val] of typeof k==='string'?[[k,v]]:Object.entries(k))this.values.set(key,structuredClone(val));}async transaction(fn){return fn(this);}}
const storeModule=import('../server/storekit-verification.mjs'),profileModule=import('../server/online-profile.mjs');
const receipt=(productId,transactionId='100')=>({transactionId,originalTransactionId:transactionId,productId,purchaseDate:1,environment:'Sandbox'});
const jws=payload=>`${Buffer.from('{}').toString('base64url')}.${Buffer.from(JSON.stringify(payload)).toString('base64url')}.signature`;
async function setup(){const {initialProfile}=await profileModule,storage=new Store(),profile=initialProfile({},'P1'),profileKey='profile:test';await storage.put(profileKey,profile);return {storage,profile,profileKey};}
test('全6商品を正式product grantへ変換',async()=>{const {applyVerifiedStoreTransaction}=await storeModule;for(const [index,id] of ['SKILL_CAT_FAKE_PAW','SKILL_POLICE_GROUP_SEARCH','SKILL_POLICE_DASH','SKILL_PACK_01','REMOVE_ADS','REMOVE_ADS_PLUS_SKILL_PACK_01'].entries()){const f=await setup(),result=await applyVerifiedStoreTransaction({...f,signedTransaction:'jws',verify:async()=>receipt(id,String(200+index))});assert.ok(result.profile.skillEntitlements.purchasedProductIds.includes(id));if(id.includes('REMOVE_ADS'))assert.equal(result.profile.skillEntitlements.adsRemoved,true);}});
test('同じtransactionId再送は二重付与しない',async()=>{const {applyVerifiedStoreTransaction}=await storeModule,f=await setup(),verify=async()=>receipt('SKILL_POLICE_DASH','300');const first=await applyVerifiedStoreTransaction({...f,signedTransaction:'jws',verify});const second=await applyVerifiedStoreTransaction({...f,profile:first.profile,signedTransaction:'jws',verify});assert.equal(first.duplicate,false);assert.equal(second.duplicate,true);assert.deepEqual(second.profile.skillEntitlements.purchasedProductIds,['SKILL_POLICE_DASH']);});
test('同じtransactionIdを別プロフィールへ付与せずappAccountTokenも照合',async()=>{const {applyVerifiedStoreTransaction}=await storeModule,f=await setup(),verify=async()=>receipt('SKILL_POLICE_DASH','301');await applyVerifiedStoreTransaction({...f,signedTransaction:'jws',verify});const other={...f.profile,playerId:'op_00000000-0000-0000-0000-000000000002'};await assert.rejects(()=>applyVerifiedStoreTransaction({storage:f.storage,profileKey:'profile:other',profile:other,signedTransaction:'jws',verify}),/store_transaction_already_claimed/);await assert.rejects(()=>applyVerifiedStoreTransaction({...f,signedTransaction:'jws',verify:async()=>({...receipt('SKILL_POLICE_DASH','302'),appAccountToken:'00000000-0000-0000-0000-000000000002'})}),/store_account_mismatch/);});
test('検証失敗・不正商品・自己申告を拒否',async()=>{const {applyVerifiedStoreTransaction}=await storeModule,f=await setup();await assert.rejects(()=>applyVerifiedStoreTransaction({...f,signedTransaction:'fake'}),/store_verification_unavailable/);await assert.rejects(()=>applyVerifiedStoreTransaction({...f,signedTransaction:'fake',verify:async()=>receipt('BAD')}),/store_transaction_not_verified/);});
test('単品所有後のPACK購入は重複せず3スキル権利になる',async()=>{const {applyVerifiedStoreTransaction}=await storeModule;const {resolveServerOwnedSkillIds}=await import('../server/skill-entitlements.mjs'),f=await setup();let one=await applyVerifiedStoreTransaction({...f,signedTransaction:'a',verify:async()=>receipt('SKILL_CAT_FAKE_PAW','401')});let pack=await applyVerifiedStoreTransaction({...f,profile:one.profile,signedTransaction:'b',verify:async()=>receipt('SKILL_PACK_01','402')});assert.deepEqual(new Set(resolveServerOwnedSkillIds(pack.profile.skillEntitlements)),new Set(['CAT_FAKE_PAW','POLICE_GROUP_SEARCH','POLICE_DASH']));});
test('Apple Server APIのSandbox照会結果を権威として検証',async()=>{const {verifyStoreKitTransaction}=await storeModule,keyPair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),pkcs8=await crypto.subtle.exportKey('pkcs8',keyPair.privateKey),privateKey=`-----BEGIN PRIVATE KEY-----\n${Buffer.from(pkcs8).toString('base64')}\n-----END PRIVATE KEY-----`,claim={transactionId:'500',originalTransactionId:'499',productId:'REMOVE_ADS',bundleId:'jp.nyanchase.game',purchaseDate:123,environment:'Sandbox'},calls=[];const result=await verifyStoreKitTransaction(jws(claim),{env:{APP_STORE_CONNECT_PRIVATE_KEY:privateKey,APP_STORE_CONNECT_KEY_ID:'KEY',APP_STORE_CONNECT_ISSUER_ID:'ISSUER',APPLE_BUNDLE_ID:'jp.nyanchase.game'},fetchFn:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({signedTransactionInfo:jws(claim)})};}});assert.equal(result.productId,'REMOVE_ADS');assert.match(calls[0].url,/api\.storekit-sandbox\.itunes\.apple\.com\/inApps\/v1\/transactions\/500$/);assert.match(calls[0].options.headers.Authorization,/^Bearer /);});
